# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. 
Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [28]:
import numpy as np

arr = np.random.uniform(low=0, high=20, size=(4, 7))
print(arr, end='\n\n')

maxVal = np.max(arr)
arr = arr / maxVal
print(arr)

[[ 6.32655459 13.83837785  1.8797996   5.95219686 19.69152927 11.90071601
  15.70394201]
 [ 1.01352527  2.07735401 12.41408285 16.68371782 11.40995394 14.10805484
   9.39099244]
 [ 0.8487023  10.36419498  4.22168784 18.63647808 10.6723228  12.34905137
  17.51258108]
 [10.14767113 18.96522547 13.47634863 11.91798959 15.10374077  7.42633724
   0.79475193]]

[[0.32128305 0.7027579  0.09546235 0.30227195 1.         0.60435712
  0.79749733]
 [0.05147011 0.1054948  0.63042757 0.84725354 0.57943463 0.71645298
  0.47690519]
 [0.04309987 0.52632758 0.21439106 0.94642106 0.54197532 0.62712505
  0.88934591]
 [0.5153318  0.96311593 0.68437288 0.60523433 0.76701716 0.3771336
  0.04036009]]


2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [29]:
import numpy as np

arr = np.random.uniform(low=0, high=10, size=(8, 10))
print(arr, end='\n\n')

maxVal = -1
index = -1
for i in range(len(arr)):
    sumVal = sum(arr[i])
    if sumVal > maxVal:
        maxVal = sumVal
        index = i

print(index)
print(arr[index])


[[3.98659369 5.09488619 8.62029679 0.45769334 7.29556084 8.75229486
  6.50910512 4.66456078 1.58616394 7.25454189]
 [7.47842765 2.40053915 6.72622773 4.91632766 9.84336928 3.14787864
  1.08199833 5.63807082 0.07145365 2.59167406]
 [2.7771402  5.87160426 0.63320307 5.36379471 6.61618471 5.2412175
  1.40598672 1.78366209 5.72271418 8.53623807]
 [2.43137493 2.89748263 6.59435723 3.12175601 2.49043347 2.15515595
  5.97499599 6.59054795 1.86479364 1.63411652]
 [6.43668829 2.0590438  3.48784659 9.69877783 1.8036225  8.52446311
  9.29973617 8.99632542 9.6914706  8.40323483]
 [4.37056129 8.52049674 5.31615763 2.51377643 1.10043514 6.24129201
  5.09058317 0.46355876 8.81775116 8.99159872]
 [2.05679629 9.06587197 4.49380484 0.37325471 4.20015258 9.24081722
  2.78768367 2.96762116 6.41761521 4.19243524]
 [4.56513308 4.2402912  9.78486223 9.20689262 6.12802993 1.9377933
  3.97116198 7.57480141 8.00583221 4.39686095]]

4
[6.43668829 2.0590438  3.48784659 9.69877783 1.8036225  8.52446311
 9.29973617

3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [30]:
import numpy as np

a = np.array([[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]])
b = np.array([[3, -1], [2, 1]])
c = np.array([[7, 21], [11, 8], [8, 4]])

x = np.dot(np.dot(np.linalg.inv(a), -1 * c), np.linalg.inv(b))
print(x)

[[ 1.00000000e+00  5.32907052e-16]
 [-2.00000000e+00  1.00000000e+00]
 [ 3.00000000e+00 -4.00000000e+00]]


## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [31]:
import numpy as np

arr = np.loadtxt('minutes_n_ingredients.csv', delimiter=',', dtype=np.int32, skiprows=1)
for i in range(5):
    print(arr[i])

[127244     60     16]
[23891    25     7]
[94746    10     6]
[67660     5     6]
[157911     60     14]


2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [32]:
import numpy as np

arr = np.loadtxt('minutes_n_ingredients.csv', delimiter=',', dtype=np.int32, skiprows=1)
s1 = np.int64(0)
s2 = np.int64(0)
c = 0
mi1 = arr[0][1]
mi2 = arr[0][2]
ma1 = arr[0][1]
ma2 = arr[0][2]

for i in arr:
    s1 += i[1]
    s2 += i[2]
    if mi1 > i[1]:
        mi1 = i[1]
    if mi2 > i[2]:
        mi2 = i[2]
    if ma1 < i[1]:
        ma1 = i[1]
    if ma2 < i[2]:
        ma2 = i[2]
    c += 1

print(f'Minutes column: Min: {mi1}, Max: {ma1}, Median: {s1 / c}')
print(f'N_ingredients column: Min: {mi2}, Max: {ma2}, Median: {s2 / c}')

Minutes column: Min: 0, Max: 2147483647, Median: 21601.00169
N_ingredients column: Min: 1, Max: 39, Median: 9.05528


In [33]:
import numpy as np

arr = np.loadtxt('minutes_n_ingredients.csv', delimiter=',', dtype=np.int32, skiprows=1)

tr = arr.transpose()
print(f'Minutes column: Min: {np.min(tr[1])}, Max: {np.max(tr[1])}, Median: {np.mean(tr[1])}')
print(f'N_ingredients column: Min: {np.min(tr[2])}, Max: {np.max(tr[2])}, Median: {np.mean(tr[2])}')

Minutes column: Min: 0, Max: 2147483647, Median: 21601.00169
N_ingredients column: Min: 1, Max: 39, Median: 9.05528


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [34]:
# Квантиль - разделитель упорядоченной выборки на равные части
qraw = 0.75

minutes = np.array(arr[:, 1])
q = np.quantile(minutes, qraw)
minutes = minutes[minutes <= q].reshape(-1, 1)
print(minutes)

[[60]
 [25]
 [10]
 ...
 [35]
 [65]
 [ 5]]


4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [35]:
import numpy as np

arr = np.loadtxt('minutes_n_ingredients.csv', delimiter=',', dtype=np.int32, skiprows=1)

column = arr[:, 1]

print(f'Число таких рецептов: {len(column[column == 0])}')
column[column == 0] = 1

print(f'Обновлённая версия:\n{arr}')

Число таких рецептов: 479
Обновлённая версия:
[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 ...
 [498432     65     15]
 [370915      5      4]
 [ 81993    140     14]]



5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [36]:
import numpy as np

arr = np.loadtxt('minutes_n_ingredients.csv', delimiter=',', dtype=np.int32, skiprows=1)
# По первому столбцу, id
print(np.unique(arr[:, 0]).size)

100000


6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [37]:
import numpy as np

arr = np.loadtxt('minutes_n_ingredients.csv', delimiter=',', dtype=np.int32, skiprows=1)
# По первому столбцу
print(f'{np.unique(arr[:, 2]).size} уникальных:')
print(np.unique(arr[:, 2]))

37 уникальных:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 37 39]


7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [38]:
print(arr[arr[:, 2] <= 5])

[[446597     15      5]
 [204134      5      3]
 [ 25623      6      4]
 ...
 [ 52088     60      5]
 [128811     15      4]
 [370915      5      4]]


8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [39]:
arr_w_easy_flag = arr[arr[:, 1] != 0]
result = arr_w_easy_flag[:, 2] / arr_w_easy_flag[:, 1]
print(f'В среднем ингредиентов приходится на одну минуту рецепта: {result}\nМаксимальное число ингредиентов на минуту рецепта: {np.max(result)}')

В среднем ингредиентов приходится на одну минуту рецепта: [0.26666667 0.28       0.6        ... 0.23076923 0.8        0.1       ]
Максимальное число ингредиентов на минуту рецепта: 23.0


9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [40]:
arr_w_easy_flag = arr[np.argsort(arr[:, 1])][::-1] # ascending
top_100_n_ingredients = arr_w_easy_flag[:100, 2]
print(np.sum(top_100_n_ingredients) / top_100_n_ingredients.size)

6.61


10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [41]:
print(arr[np.random.randint(0, len(arr), 10)])

[[326328     25      7]
 [115764    195     11]
 [172486     40      8]
 [501178     90     17]
 [306160     40      7]
 [424938     40      8]
 [521673    150     18]
 [ 37469     45      9]
 [284765     25      4]
 [237649    375     11]]


11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [42]:
n_ingredients = arr[:, 2]
med = np.median(n_ingredients)
percent = n_ingredients[n_ingredients < med].size / n_ingredients.size * 100
print(percent)

48.217


12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [43]:
mask = (arr[:, 1] <= 20) & (arr[:, 2] <= 5)

easy_recipe = np.arange(len(arr)).reshape(-1, 1)
easy_recipe[mask] = 1
# Обратная маска
easy_recipe[~mask] = 0
# Присоединить столбец вдоль существующей оси
arr_w_easy_flag = np.concatenate((arr, easy_recipe), axis=1)
print(arr_w_easy_flag)

[[127244     60     16      0]
 [ 23891     25      7      0]
 [ 94746     10      6      0]
 ...
 [498432     65     15      0]
 [370915      5      4      1]
 [ 81993    140     14      0]]


13. Выведите процент "простых" рецептов в датасете

In [44]:
last_column = np.array(arr_w_easy_flag[:, 3])
percent = len(last_column[last_column == 1]) / len(arr_w_easy_flag)
print(percent)

0.09552


14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [46]:
short_recipes = arr[arr[:, 1] < 10]
standard_recipes = arr[(arr[:, 1] >= 10) & (arr[:, 1] < 20)]
long_recipes = arr[arr[:, 1] >= 20]

max_amount = max(short_recipes.shape[0], standard_recipes.shape[0], long_recipes.shape[0])

# Трехмерный массив
result = np.zeros((3, max_amount, arr.shape[1]))

result[0, :short_recipes.shape[0]] = short_recipes[:max_amount]
result[1, :standard_recipes.shape[0]] = standard_recipes[:max_amount]
result[2, :long_recipes.shape[0]] = long_recipes[:max_amount]

print(result.shape)

(3, 79751, 3)
