# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. 
Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [3]:
import numpy as np

arr = np.random.uniform(low=0, high=20, size=(4, 7))
print(arr, end='\n\n')

maxVal = np.max(arr)
arr = arr / maxVal
print(arr)

[[ 5.08227726  0.12822001 15.70024057  8.66892575  8.49247629  0.85771482
  12.76478894]
 [19.76971737  7.83350996  9.91815074  7.28145622  5.20727668 19.38441295
  13.28401729]
 [ 1.92922902 12.92634677 19.15433301 14.34685378 10.04396812  8.2776282
   9.64962822]
 [ 5.46057769  1.18632886 18.05820566  5.38635766  1.4680205   5.01019661
  11.81470175]]

[[0.25707384 0.00648568 0.79415605 0.43849518 0.42956994 0.04338528
  0.64567382]
 [1.         0.39623783 0.50168399 0.36831362 0.26339662 0.98051037
  0.67193764]
 [0.09758506 0.6538458  0.96887237 0.72569848 0.50804814 0.4187024
  0.48810148]
 [0.27620919 0.06000738 0.91342761 0.27245497 0.07425602 0.25342783
  0.59761612]]


2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [6]:
import numpy as np

arr = np.random.uniform(low=0, high=10, size=(8, 10))
print(arr, end='\n\n')

maxVal = -1
index = -1
for i in range(len(arr)):
    sumVal = sum(arr[i])
    if sumVal > maxVal:
        maxVal = sumVal
        index = i

print(index)
print(arr[index])


[[2.48673056 7.29194779 0.05168548 3.03990659 4.03428935 3.0123276
  9.48652138 8.45189176 2.46180651 8.79717112]
 [0.31811425 2.05238751 0.19190597 2.87311901 8.48186854 3.3489208
  7.5742734  2.69097283 7.70550933 6.07012474]
 [3.80828104 0.59669538 3.80276558 0.75141469 8.9320164  0.4973536
  5.35559425 5.26297315 4.65418545 7.67566638]
 [9.09131559 8.49085833 2.52389553 3.78757229 0.56496073 5.98931417
  5.79152816 0.79127558 3.03488952 7.95943751]
 [9.30438649 2.52012268 8.43375033 4.46428374 2.40098746 6.14968697
  7.61503834 0.75775048 7.45525837 4.77200264]
 [1.75616895 1.04468722 5.98287493 6.55239362 9.35360247 9.51586899
  9.87958005 8.85190716 9.33106381 8.2234106 ]
 [2.68259294 3.64731866 5.08545612 3.62365874 0.41858869 7.26591217
  0.92484794 1.47536029 5.4137768  7.44228506]
 [8.38465829 3.04264294 8.40231716 9.82101339 4.56165947 9.05050032
  5.62846515 8.8879086  4.22995426 4.29520042]]

5
[1.75616895 1.04468722 5.98287493 6.55239362 9.35360247 9.51586899
 9.87958005 

3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [ ]:
import numpy as np

a = np.array([[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]])
b = np.array([[3, -1], [2, 1]])
c = np.array([[7, 21], [11, 8], [8, 4]])

x = np.dot(np.dot(np.linalg.inv(a), -1 * c), np.linalg.inv(b))
print(x)

## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [3]:
import numpy as np

arr = np.loadtxt('minutes_n_ingredients.csv', delimiter=',', dtype=np.int32, skiprows=1)
for i in range(5):
    print(arr[i])

[127244     60     16]
[23891    25     7]
[94746    10     6]
[67660     5     6]
[157911     60     14]


2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [5]:
import numpy as np

arr = np.loadtxt('minutes_n_ingredients.csv', delimiter=',', dtype=np.int32, skiprows=1)
s1 = np.int64(0)
s2 = np.int64(0)
c = 0
mi1 = arr[0][1]
mi2 = arr[0][2]
ma1 = arr[0][1]
ma2 = arr[0][2]

for i in arr:
    s1 += i[1]
    s2 += i[2]
    if mi1 > i[1]:
        mi1 = i[1]
    if mi2 > i[2]:
        mi2 = i[2]
    if ma1 < i[1]:
        ma1 = i[1]
    if ma2 < i[2]:
        ma2 = i[2]
    c += 1

print(f'Minutes column: Min: {mi1}, Max: {ma1}, Median: {s1 / c}')
print(f'N_ingredients column: Min: {mi2}, Max: {ma2}, Median: {s2 / c}')

Minutes column: Min: 0, Max: 2147483647, Median: 21601.00169
N_ingredients column: Min: 1, Max: 39, Median: 9.05528


In [6]:
import numpy as np

arr = np.loadtxt('minutes_n_ingredients.csv', delimiter=',', dtype=np.int32, skiprows=1)

tr = arr.transpose()
print(f'Minutes column: Min: {np.min(tr[1])}, Max: {np.max(tr[1])}, Median: {np.mean(tr[1])}')
print(f'N_ingredients column: Min: {np.min(tr[2])}, Max: {np.max(tr[2])}, Median: {np.mean(tr[2])}')

Minutes column: Min: 0, Max: 2147483647, Median: 21601.00169
N_ingredients column: Min: 1, Max: 39, Median: 9.05528


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [10]:
import numpy as np

arr = np.loadtxt('minutes_n_ingredients.csv', delimiter=',', dtype=np.int32, skiprows=1)

column = arr[:, 1]
column[column == 0] = 1

print(arr)

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 ...
 [498432     65     15]
 [370915      5      4]
 [ 81993    140     14]]


5. Посчитайте, сколько уникальных рецептов находится в датасете.

6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

10. Выберите случайным образом и выведите информацию о 10 различных рецептах

11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

13. Выведите процент "простых" рецептов в датасете

14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.